# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fostyr/Desktop/Code/C/digsim-94

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fostyr/Desktop/Code/C/digsim-94

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/fostyr/Desktop/Code/C/digsim-94/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fostyr/Desktop/Code/C/digsim-94/CMakeFiles /home/fostyr/Desktop/Code/C/digsim-94//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fostyr/Desktop/Code/C/digsim-94/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named digsim-94

# Build rule for target.
digsim-94: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 digsim-94
.PHONY : digsim-94

# fast build rule for target.
digsim-94/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/digsim-94.dir/build.make CMakeFiles/digsim-94.dir/build
.PHONY : digsim-94/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f _deps/raylib-build/CMakeFiles/uninstall.dir/build.make _deps/raylib-build/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named raylib

# Build rule for target.
raylib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raylib
.PHONY : raylib

# fast build rule for target.
raylib/fast:
	$(MAKE) $(MAKESILENT) -f _deps/raylib-build/raylib/CMakeFiles/raylib.dir/build.make _deps/raylib-build/raylib/CMakeFiles/raylib.dir/build
.PHONY : raylib/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/glfw.dir/build.make _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/update_mappings.dir/build.make _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

src/e_behaviour.o: src/e_behaviour.c.o
.PHONY : src/e_behaviour.o

# target to build an object file
src/e_behaviour.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/digsim-94.dir/build.make CMakeFiles/digsim-94.dir/src/e_behaviour.c.o
.PHONY : src/e_behaviour.c.o

src/e_behaviour.i: src/e_behaviour.c.i
.PHONY : src/e_behaviour.i

# target to preprocess a source file
src/e_behaviour.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/digsim-94.dir/build.make CMakeFiles/digsim-94.dir/src/e_behaviour.c.i
.PHONY : src/e_behaviour.c.i

src/e_behaviour.s: src/e_behaviour.c.s
.PHONY : src/e_behaviour.s

# target to generate assembly for a file
src/e_behaviour.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/digsim-94.dir/build.make CMakeFiles/digsim-94.dir/src/e_behaviour.c.s
.PHONY : src/e_behaviour.c.s

src/e_render.o: src/e_render.c.o
.PHONY : src/e_render.o

# target to build an object file
src/e_render.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/digsim-94.dir/build.make CMakeFiles/digsim-94.dir/src/e_render.c.o
.PHONY : src/e_render.c.o

src/e_render.i: src/e_render.c.i
.PHONY : src/e_render.i

# target to preprocess a source file
src/e_render.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/digsim-94.dir/build.make CMakeFiles/digsim-94.dir/src/e_render.c.i
.PHONY : src/e_render.c.i

src/e_render.s: src/e_render.c.s
.PHONY : src/e_render.s

# target to generate assembly for a file
src/e_render.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/digsim-94.dir/build.make CMakeFiles/digsim-94.dir/src/e_render.c.s
.PHONY : src/e_render.c.s

src/e_storage.o: src/e_storage.c.o
.PHONY : src/e_storage.o

# target to build an object file
src/e_storage.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/digsim-94.dir/build.make CMakeFiles/digsim-94.dir/src/e_storage.c.o
.PHONY : src/e_storage.c.o

src/e_storage.i: src/e_storage.c.i
.PHONY : src/e_storage.i

# target to preprocess a source file
src/e_storage.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/digsim-94.dir/build.make CMakeFiles/digsim-94.dir/src/e_storage.c.i
.PHONY : src/e_storage.c.i

src/e_storage.s: src/e_storage.c.s
.PHONY : src/e_storage.s

# target to generate assembly for a file
src/e_storage.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/digsim-94.dir/build.make CMakeFiles/digsim-94.dir/src/e_storage.c.s
.PHONY : src/e_storage.c.s

src/e_world.o: src/e_world.c.o
.PHONY : src/e_world.o

# target to build an object file
src/e_world.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/digsim-94.dir/build.make CMakeFiles/digsim-94.dir/src/e_world.c.o
.PHONY : src/e_world.c.o

src/e_world.i: src/e_world.c.i
.PHONY : src/e_world.i

# target to preprocess a source file
src/e_world.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/digsim-94.dir/build.make CMakeFiles/digsim-94.dir/src/e_world.c.i
.PHONY : src/e_world.c.i

src/e_world.s: src/e_world.c.s
.PHONY : src/e_world.s

# target to generate assembly for a file
src/e_world.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/digsim-94.dir/build.make CMakeFiles/digsim-94.dir/src/e_world.c.s
.PHONY : src/e_world.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/digsim-94.dir/build.make CMakeFiles/digsim-94.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/digsim-94.dir/build.make CMakeFiles/digsim-94.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/digsim-94.dir/build.make CMakeFiles/digsim-94.dir/src/main.c.s
.PHONY : src/main.c.s

src/player.o: src/player.c.o
.PHONY : src/player.o

# target to build an object file
src/player.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/digsim-94.dir/build.make CMakeFiles/digsim-94.dir/src/player.c.o
.PHONY : src/player.c.o

src/player.i: src/player.c.i
.PHONY : src/player.i

# target to preprocess a source file
src/player.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/digsim-94.dir/build.make CMakeFiles/digsim-94.dir/src/player.c.i
.PHONY : src/player.c.i

src/player.s: src/player.c.s
.PHONY : src/player.s

# target to generate assembly for a file
src/player.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/digsim-94.dir/build.make CMakeFiles/digsim-94.dir/src/player.c.s
.PHONY : src/player.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... digsim-94"
	@echo "... glfw"
	@echo "... raylib"
	@echo "... src/e_behaviour.o"
	@echo "... src/e_behaviour.i"
	@echo "... src/e_behaviour.s"
	@echo "... src/e_render.o"
	@echo "... src/e_render.i"
	@echo "... src/e_render.s"
	@echo "... src/e_storage.o"
	@echo "... src/e_storage.i"
	@echo "... src/e_storage.s"
	@echo "... src/e_world.o"
	@echo "... src/e_world.i"
	@echo "... src/e_world.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/player.o"
	@echo "... src/player.i"
	@echo "... src/player.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

